name: DAST Scan with ZAP (Authenticated)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Start OWASP Juice Shop Container
        run: |
          docker run -d -p 8080:3000 --name juice-shop bkimminich/juice-shop
          echo "Waiting for Juice Shop to start..."
          sleep 30
          echo "Juice Shop should be running on http://localhost:8080"

      - name: Create ZAP Automation Plan for Authenticated Scan
        id: create_zap_plan
        run: |
          cat << 'EOF' > zap-automation-plan.yaml
          env:
            contexts:
              - name: "JuiceShopContext"
                urls:
                  - "http://localhost:8080"
                authentication:
                  method: "formBased"
                  parameters:
                    loginPageUrl: "http://localhost:8080/#/login"
                    loginRequestUrl: "http://localhost:8080/rest/user/login"
                    loginRequestBody: "email={%username%}&password={%password%}"
                  verification:
                    method: "response"
                    loggedInRegex: "Logout"
                    loggedOutRegex: "Login"
                users:
                  - name: "adminuser"
                    credentials:
                      username: "admin@juice-sh.op"
                      password: "admin"
            parameters:
              failOnError: true
              failOnWarning: false

          jobs:
            - type: spider
              name: spider
              parameters:
                context: "JuiceShopContext"
                user: "adminuser"

            - type: activeScan
              name: activescan
              parameters:
                context: "JuiceShopContext"
                user: "adminuser"

            - type: report
              name: report
              parameters:
                template: "sarif-json"
                filename: "zap-report.sarif"
          EOF
          echo "ZAP Automation Plan created."

      - name: Run ZAP Authenticated Scan
        run: |
          ZAP_IMAGE="ghcr.io/zaproxy/zaproxy:stable"

          echo "Pulling latest ZAP image..."
          docker pull "${ZAP_IMAGE}"

          echo "Running ZAP scan..."
          docker run --rm \
            -v $(pwd):/zap/wrk \
            "${ZAP_IMAGE}" zap.sh -cmd -autorun /zap/wrk/zap-automation-plan.yaml

          echo "ZAP authenticated scan completed."

      - name: Upload ZAP SARIF Report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: zap-report.sarif
          category: dast-owasp-zap-authenticated

      - name: Upload Other Reports (if any)
        uses: actions/upload-artifact@v4
        with:
          name: other-dast-reports
          path: |
            zap-report.sarif
          retention-days: 5
